apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-cd-react-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ci-cd-react-k8s
  template:
    metadata:
      labels:
        app: ci-cd-react-k8s
    spec:
      containers:
      - name: ci-cd-react-k8s
        restartPolicy: Always
        image: $(CONTAINER_REGISTRY)/$(IMAGE_NAME):latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "2024Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health_check
            port: 5153
          initialDelaySeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: "/readiness_check"
            port: 5153
          initialDelaySeconds: 5
          timeoutSeconds: 5
        env:
        - name: CONTAINER_REGISTRY
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: CONTAINER_REGISTRY
        - name: IMAGE_NAME
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: IMAGE_NAME