name: Deploy to Kubernetes

on:
  workflow_dispatch:
# push:
#   branches:
#     - main

jobs:
  deploy-k8s:
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to container registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: 0987432592345457/test-react:latest

    # - name: Set up kubectl
    #   uses: azure/setup-kubectl@v2
    #   with:
    #     version: 'latest'

    - uses: marcofranssen/setup-kubectl@v0.3.0
      id: kubectl
      with:
        kubectlVersion: v1.28.9
    - run: echo ${{ steps.kubectl.output.kubectl-version }}

    - name: Deploy to Kubernetes
      run: |
        # echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
        aws eks update-kubeconfig --name udagram --region us-east-1
        # kubectl config current-context
        kubectl apply -f deployment/deployment.yml 
        # kubectl apply -f deployment/deployment.yml --kubeconfig=kubeconfig.yaml